### ISSUE TITLE
How to remove | bar at the beginning of child rows in tree . 

### ISSUE THREAD

**Issue by Suprit-S-M** [reactabular/reactabular#239]

**Comment by bebraw** [comment]
You should modify the styling. See [here](https://github.com/reactabular/reactabular/blob/master/packages/reactabular-tree/style.css) for defaults. Instead of

```css
.has-parent:not(.has-children):before {
  padding-right: 0.5em;
  content: "\0007C";
  font-size: large;
}
```

you probably want a rule without `content`.
